// <auto-generated />
using Group3_14_Project2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Group3_14_Project2.Migrations
{
    [DbContext(typeof(TourTimesContext))]
    [Migration("20220321194502_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Group3_14_Project2.Models.TourTimes", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time10")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time11")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time12")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time13")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time5")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time6")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time7")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time8")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time9")
                        .HasColumnType("TEXT");

                    b.HasKey("Date");

                    b.ToTable("TourTimes");

                    b.HasData(
                        new
                        {
                            Date = "3/23/2022",
                            DayName = "Wednesday",
                            Time1 = "8 AM",
                            Time10 = "5 PM",
                            Time11 = "6 PM",
                            Time12 = "7 PM",
                            Time13 = "8 PM",
                            Time2 = "9 AM",
                            Time3 = "10 AM",
                            Time4 = "11 AM",
                            Time5 = "12 AM",
                            Time6 = "1 PM",
                            Time7 = "2 PM",
                            Time8 = "3 PM",
                            Time9 = "4 PM"
                        },
                        new
                        {
                            Date = "3/24/2022",
                            DayName = "Thursday",
                            Time1 = "8 AM",
                            Time10 = "5 PM",
                            Time11 = "6 PM",
                            Time12 = "7 PM",
                            Time13 = "8 PM",
                            Time2 = "9 AM",
                            Time3 = "10 AM",
                            Time4 = "11 AM",
                            Time5 = "12 AM",
                            Time6 = "1 PM",
                            Time7 = "2 PM",
                            Time8 = "3 PM",
                            Time9 = "4 PM"
                        },
                        new
                        {
                            Date = "3/25/2022",
                            DayName = "Friday",
                            Time1 = "8 AM",
                            Time10 = "5 PM",
                            Time11 = "6 PM",
                            Time12 = "7 PM",
                            Time13 = "8 PM",
                            Time2 = "9 AM",
                            Time3 = "10 AM",
                            Time4 = "11 AM",
                            Time5 = "12 AM",
                            Time6 = "1 PM",
                            Time7 = "2 PM",
                            Time8 = "3 PM",
                            Time9 = "4 PM"
                        },
                        new
                        {
                            Date = "3/26/2022",
                            DayName = "Saturday",
                            Time1 = "8 AM",
                            Time10 = "5 PM",
                            Time11 = "6 PM",
                            Time12 = "7 PM",
                            Time13 = "8 PM",
                            Time2 = "9 AM",
                            Time3 = "10 AM",
                            Time4 = "11 AM",
                            Time5 = "12 AM",
                            Time6 = "1 PM",
                            Time7 = "2 PM",
                            Time8 = "3 PM",
                            Time9 = "4 PM"
                        },
                        new
                        {
                            Date = "3/27/2022",
                            DayName = "Sunday",
                            Time1 = "8 AM",
                            Time10 = "5 PM",
                            Time11 = "6 PM",
                            Time12 = "7 PM",
                            Time13 = "8 PM",
                            Time2 = "9 AM",
                            Time3 = "10 AM",
                            Time4 = "11 AM",
                            Time5 = "12 AM",
                            Time6 = "1 PM",
                            Time7 = "2 PM",
                            Time8 = "3 PM",
                            Time9 = "4 PM"
                        },
                        new
                        {
                            Date = "3/28/2022",
                            DayName = "Monday",
                            Time1 = "8 AM",
                            Time10 = "5 PM",
                            Time11 = "6 PM",
                            Time12 = "7 PM",
                            Time13 = "8 PM",
                            Time2 = "9 AM",
                            Time3 = "10 AM",
                            Time4 = "11 AM",
                            Time5 = "12 AM",
                            Time6 = "1 PM",
                            Time7 = "2 PM",
                            Time8 = "3 PM",
                            Time9 = "4 PM"
                        },
                        new
                        {
                            Date = "3/29/2022",
                            DayName = "Tuesday",
                            Time1 = "8 AM",
                            Time10 = "5 PM",
                            Time11 = "6 PM",
                            Time12 = "7 PM",
                            Time13 = "8 PM",
                            Time2 = "9 AM",
                            Time3 = "10 AM",
                            Time4 = "11 AM",
                            Time5 = "12 AM",
                            Time6 = "1 PM",
                            Time7 = "2 PM",
                            Time8 = "3 PM",
                            Time9 = "4 PM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
