// <auto-generated />
using Group3_14_Project2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Group3_14_Project2.Migrations
{
    [DbContext(typeof(TourTimesContext))]
    partial class TourTimesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Group3_14_Project2.Models.Appointments", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TourId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Group3_14_Project2.Models.TourTimes", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Available1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available10")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available11")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available12")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available13")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available6")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available7")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available8")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available9")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time10")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time11")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time12")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time13")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time5")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time6")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time7")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time8")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time9")
                        .HasColumnType("TEXT");

                    b.HasKey("Date");

                    b.ToTable("Times");

                    b.HasData(
                        new
                        {
                            Date = "3/23/2022",
                            Available1 = true,
                            Available10 = true,
                            Available11 = true,
                            Available12 = true,
                            Available13 = true,
                            Available2 = true,
                            Available3 = true,
                            Available4 = true,
                            Available5 = true,
                            Available6 = true,
                            Available7 = true,
                            Available8 = true,
                            Available9 = true,
                            DayName = "Wednesday",
                            Time1 = "8 AM",
                            Time10 = "5 PM",
                            Time11 = "6 PM",
                            Time12 = "7 PM",
                            Time13 = "8 PM",
                            Time2 = "9 AM",
                            Time3 = "10 AM",
                            Time4 = "11 AM",
                            Time5 = "12 AM",
                            Time6 = "1 PM",
                            Time7 = "2 PM",
                            Time8 = "3 PM",
                            Time9 = "4 PM"
                        },
                        new
                        {
                            Date = "3/24/2022",
                            Available1 = true,
                            Available10 = true,
                            Available11 = true,
                            Available12 = true,
                            Available13 = true,
                            Available2 = true,
                            Available3 = true,
                            Available4 = true,
                            Available5 = true,
                            Available6 = true,
                            Available7 = true,
                            Available8 = true,
                            Available9 = true,
                            DayName = "Thursday",
                            Time1 = "8 AM",
                            Time10 = "5 PM",
                            Time11 = "6 PM",
                            Time12 = "7 PM",
                            Time13 = "8 PM",
                            Time2 = "9 AM",
                            Time3 = "10 AM",
                            Time4 = "11 AM",
                            Time5 = "12 AM",
                            Time6 = "1 PM",
                            Time7 = "2 PM",
                            Time8 = "3 PM",
                            Time9 = "4 PM"
                        },
                        new
                        {
                            Date = "3/25/2022",
                            Available1 = true,
                            Available10 = true,
                            Available11 = true,
                            Available12 = true,
                            Available13 = true,
                            Available2 = true,
                            Available3 = true,
                            Available4 = true,
                            Available5 = true,
                            Available6 = true,
                            Available7 = true,
                            Available8 = true,
                            Available9 = true,
                            DayName = "Friday",
                            Time1 = "8 AM",
                            Time10 = "5 PM",
                            Time11 = "6 PM",
                            Time12 = "7 PM",
                            Time13 = "8 PM",
                            Time2 = "9 AM",
                            Time3 = "10 AM",
                            Time4 = "11 AM",
                            Time5 = "12 AM",
                            Time6 = "1 PM",
                            Time7 = "2 PM",
                            Time8 = "3 PM",
                            Time9 = "4 PM"
                        },
                        new
                        {
                            Date = "3/26/2022",
                            Available1 = true,
                            Available10 = true,
                            Available11 = true,
                            Available12 = true,
                            Available13 = true,
                            Available2 = true,
                            Available3 = true,
                            Available4 = true,
                            Available5 = true,
                            Available6 = true,
                            Available7 = true,
                            Available8 = true,
                            Available9 = true,
                            DayName = "Saturday",
                            Time1 = "8 AM",
                            Time10 = "5 PM",
                            Time11 = "6 PM",
                            Time12 = "7 PM",
                            Time13 = "8 PM",
                            Time2 = "9 AM",
                            Time3 = "10 AM",
                            Time4 = "11 AM",
                            Time5 = "12 AM",
                            Time6 = "1 PM",
                            Time7 = "2 PM",
                            Time8 = "3 PM",
                            Time9 = "4 PM"
                        },
                        new
                        {
                            Date = "3/27/2022",
                            Available1 = true,
                            Available10 = true,
                            Available11 = true,
                            Available12 = true,
                            Available13 = true,
                            Available2 = true,
                            Available3 = true,
                            Available4 = true,
                            Available5 = true,
                            Available6 = true,
                            Available7 = true,
                            Available8 = true,
                            Available9 = true,
                            DayName = "Sunday",
                            Time1 = "8 AM",
                            Time10 = "5 PM",
                            Time11 = "6 PM",
                            Time12 = "7 PM",
                            Time13 = "8 PM",
                            Time2 = "9 AM",
                            Time3 = "10 AM",
                            Time4 = "11 AM",
                            Time5 = "12 AM",
                            Time6 = "1 PM",
                            Time7 = "2 PM",
                            Time8 = "3 PM",
                            Time9 = "4 PM"
                        },
                        new
                        {
                            Date = "3/28/2022",
                            Available1 = true,
                            Available10 = true,
                            Available11 = true,
                            Available12 = true,
                            Available13 = true,
                            Available2 = true,
                            Available3 = true,
                            Available4 = true,
                            Available5 = true,
                            Available6 = true,
                            Available7 = true,
                            Available8 = true,
                            Available9 = true,
                            DayName = "Monday",
                            Time1 = "8 AM",
                            Time10 = "5 PM",
                            Time11 = "6 PM",
                            Time12 = "7 PM",
                            Time13 = "8 PM",
                            Time2 = "9 AM",
                            Time3 = "10 AM",
                            Time4 = "11 AM",
                            Time5 = "12 AM",
                            Time6 = "1 PM",
                            Time7 = "2 PM",
                            Time8 = "3 PM",
                            Time9 = "4 PM"
                        },
                        new
                        {
                            Date = "3/29/2022",
                            Available1 = true,
                            Available10 = true,
                            Available11 = true,
                            Available12 = true,
                            Available13 = true,
                            Available2 = true,
                            Available3 = true,
                            Available4 = true,
                            Available5 = true,
                            Available6 = true,
                            Available7 = true,
                            Available8 = true,
                            Available9 = true,
                            DayName = "Tuesday",
                            Time1 = "8 AM",
                            Time10 = "5 PM",
                            Time11 = "6 PM",
                            Time12 = "7 PM",
                            Time13 = "8 PM",
                            Time2 = "9 AM",
                            Time3 = "10 AM",
                            Time4 = "11 AM",
                            Time5 = "12 AM",
                            Time6 = "1 PM",
                            Time7 = "2 PM",
                            Time8 = "3 PM",
                            Time9 = "4 PM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
