// <auto-generated />
using Group3_14_Project2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Group3_14_Project2.Migrations
{
    [DbContext(typeof(TourTimesContext))]
    partial class TourTimesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");
#pragma warning restore 612, 618
        }
    }
}
